{% set version = "2.2.11" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-opencpu
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/opencpu_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/opencpu/opencpu_{{ version }}.tar.gz
  sha256: 7a80dca3c1c712e89c887c206c03de4487e4402a4d41563344bb76c4fe72bbc1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip      # [win]
  host:
    - r-base
    - r-brew
    - r-curl >=4.0
    - r-evaluate >=0.12
    - r-httpuv >=1.3
    - r-jsonlite >=1.4
    - r-knitr >=1.6
    - r-mime
    - r-openssl
    - r-protolite
    - r-rappdirs
    - r-remotes >=2.0.2
    - r-rlang
    - r-sys >=2.1
    - r-vctrs
    - r-webutils >=0.6
    - r-zip
  run:
    - r-base
    - r-brew
    - r-curl >=4.0
    - r-evaluate >=0.12
    - r-httpuv >=1.3
    - r-jsonlite >=1.4
    - r-knitr >=1.6
    - r-mime
    - r-openssl
    - r-protolite
    - r-rappdirs
    - r-remotes >=2.0.2
    - r-rlang
    - r-sys >=2.1
    - r-vctrs
    - r-webutils >=0.6
    - r-zip

test:
  commands:
    - $R -e "library('opencpu')"           # [not win]
    - "\"%R%\" -e \"library('opencpu')\""  # [win]

about:
  home: https://www.opencpu.org
  dev_url: https://github.com/opencpu/opencpu
  license: Apache-2.0
  summary: A system for embedded scientific computing and reproducible research with R. The OpenCPU server exposes a simple but powerful HTTP api for RPC and data interchange with R. This provides a reliable and scalable foundation for statistical services or  building R web applications. The OpenCPU server runs either as
    a single-user development server within the interactive R session, or as a multi-user Linux stack based on Apache2.  The entire system is fully open source and permissively licensed. The OpenCPU website has detailed documentation and example apps.
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
