appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mbpD8ma+zkMqxYycA1OmgTX/+6G1S5vGG5SICy4Gj9S6/8oQC0HhteBeQEXvrM8G21yGbIG4/+Rq0nD8UryLQFNcOCtFM2gjnRUUNHSaEufYlzve67U2V8hBjyJridP8qGAmkipBczHJXl4DpJKsx5E1DLPjaR2fMH3vJLVrdhp5OFZfh/6tXx1y0SHHB+RvgIPNyhiYEStc8hd056tc0Q02PB1KB3YN/UPIcpucQVOpm/goSUb8BqiYnIKRbHhhvSm7W2LWJr7W/+I3eeG247/k4d1JLLc6oDT4zvZRmtCti3nl/htLgATKxl/c14DYuu46Fc3S+JlgBxWxJnRiWfhrUacNyXacW7XDhYFP/EfjAbYhO0aeMYsU/VCYROvPC7oTg5zvrD19PZheTH4WI9c/G19FZumdTIMF2OOaSpWF6r3X8qMIr/2bdwsEvUCx3EZ8/YQomEcejmHZnkF8Qf7XNk3YxeoceCCgTcrozH4foqk3lAvaEHqw1GvLqRxba+24D4RcFJ6gPyn1pm9S9FAG2xBaZ4h1xu9B05C/52tRkbG8pZ3Zaexgg2JTolMcBmd4oD5XEI7WB8DgdXQwdyjV0ILhv9p5EZ3YGC1aDlilULHk88k/rUOSrcHcrkhMfs+FzT/nWqB8Jxe+27Y95lWu3U+o6fvDrYSeUbZyzWY=}
